# -*- coding: utf-8 -*-
"""Untitled7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eY95o-GiwJMwYAYmhE68GkbUCu7SGa4K
"""

!pip install fastapi uvicorn requests python-dotenv

HEALTH_CHAIN_API_KEY=""

import os
from dotenv import load_dotenv

load_dotenv()

# The key is directly defined in cell PgIAWMrIJZCi, so os.getenv will not work here
# We will use the key defined directly if os.getenv returns nothing.
_temp_key_from_env = os.getenv("HEALTH_CHAIN_API_KEY")
if _temp_key_from_env:
    HEALTH_CHAIN_API_KEY = _temp_key_from_env

print(f"HEALTH_CHAIN_API_KEY is set: {bool(HEALTH_CHAIN_API_KEY)}")

from fastapi import FastAPI
from fastapi.responses import JSONResponse
from pydantic import BaseModel
import requests

app = FastAPI(title="Automated Health Alerts API")

class UserHealthData(BaseModel):
    sleep_hours: float
    water_intake: str
    exercise_per_week: int

def generate_alerts(data: UserHealthData):
    alerts = []

    if data.sleep_hours < 5:
        alerts.append("Low sleep detected")

    if data.water_intake.lower() == "low":
        alerts.append("Low water intake detected")

    if data.exercise_per_week < 2:
        alerts.append("Low physical activity detected")

    return alerts

import requests

def improve_alerts_with_ai(alerts):

    if not alerts:
        return ["No major health concerns detected. Keep it up!"]

    prompt = f"""
    You are a friendly health assistant.

    Rewrite these alerts in a supportive, human-friendly tone.
    Do NOT diagnose diseases.

    Alerts:
    {alerts}
    """

    url = "https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent"

    headers = {"Content-Type": "application/json"}
    params = {"key": HEALTH_CHAIN_API_KEY}

    payload = {
        "contents": [
            {"role": "user", "parts": [{"text": prompt}]}
        ]
    }

    try:
        response = requests.post(url, headers=headers, params=params, json=payload)
        response.raise_for_status() # Raise an exception for bad status codes (4xx or 5xx)
        result = response.json()

        # Check if 'candidates' and 'parts' exist in the response
        if 'candidates' in result and result['candidates'] and 'content' in result['candidates'][0] and 'parts' in result['candidates'][0]['content'] and result['candidates'][0]['content']['parts']:
            text = result["candidates"][0]["content"]["parts"][0]["text"]
            return text.split("\n")
        else:
            print(f"Warning: Unexpected API response structure: {result}")
            return alerts # Fallback to original alerts

    except requests.exceptions.RequestException as e:
        print(f"API Request failed: {e}")
        if e.response is not None:
            print(f"API Response Status Code: {e.response.status_code}")
            print(f"API Response Body: {e.response.text}")
        return alerts
    except Exception as e:
        print(f"An unexpected error occurred: {e}")
        return alerts

@app.post("/alerts/check")
def check_alerts(user_data: UserHealthData):

    raw_alerts = generate_alerts(user_data)
    final_alerts = improve_alerts_with_ai(raw_alerts)

    return JSONResponse(content={
        "status": "success",
        "alerts": final_alerts
    })

# Dummy test object
class Dummy:
    sleep_hours = 4
    water_intake = "low"
    exercise_per_week = 0

print(" Alerts:\n")
print(improve_alerts_with_ai(generate_alerts(Dummy)))



# Dummy test object
class Dummy:
    sleep_hours = 4
    water_intake = "low"
    exercise_per_week = 0

print(" Alerts:\n")
print(improve_alerts_with_ai(generate_alerts(Dummy)))

