# -*- coding: utf-8 -*-
"""Health chain Ai chatbot

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HPpgoIVbaTObqjfZ7YOQ_6NRKJbzx3eD

INSTALL DEPENDENCIES
"""

"""IMPORTS LIBARIES"""

import google.generativeai as genai
from fastapi import FastAPI, Query
from fastapi.responses import JSONResponse
import nest_asyncio
from pyngrok import ngrok
from dotenv import load_dotenv
import os
import uvicorn

"""loading dotenv files"""
load_dotenv()

"""CONFIGURE GEMINI API"""

GEMINI_API_KEY = os.getenv("HEALTH_CHAIN_API_KEY")
genai.configure(api_key=GEMINI_API_KEY)

"""Initialize Gemini model with Google Search grounding enabled"""

from google.generativeai.protos import GoogleSearchRetrieval # Import this for correct tool configuration

model = genai.GenerativeModel(
    model_name="gemini-2.5-flash",
    # Correct way to enable Google Search Retrieval as a tool
    tools=[genai.Tool(google_search_retrieval=GoogleSearchRetrieval())]
)

"""SYSTEM PROMPT"""

SYSTEM_PROMPT = """
You are a friendly, supportive, non-diagnostic community health assistant.
Provide safe, factual information about general and community health topics.
Never offer prescriptions, diagnoses, or treatment plans.
Encourage users to visit licensed medical professionals when necessary.
"""

"""CONTEXTUAL PROMPTING LOGIC"""

def build_prompt(user_query):
    q = user_query.lower()
    if "malaria" in q or "alert" in q:
        context = "Context: User is asking about a malaria alert or prevention measures."
    elif "vaccine" in q or "vaccination" in q:
        context = "Context: User is asking about vaccines or immunization schedules."
    elif "blood" in q and "donate" in q:
        context = "Context: User is asking about blood donation or donor eligibility."
    else:
        context = "Context: General community health inquiry."

    full_prompt = f"{SYSTEM_PROMPT}\n\n{context}\n\nUser: {user_query}"
    return full_prompt

"""GEMINI RESPONSE HANDLER"""

def chatbot_response(user_query):
    import requests

    # Gemini API endpoint
    url = "https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash:generateContent"
    headers = {"Content-Type": "application/json"}
    params = {"key": GEMINI_API_KEY}

    #  System + user prompt
    prompt = f"""
    You are a friendly, helpful, and non-diagnostic community health assistant named Health Assistant.
    Your role is to provide safe, educational, and verified health information.
    You must avoid giving medical diagnoses or prescriptions.
    Include reliable external sources (like WHO, CDC, or health.gov) when appropriate.

    Context: The user is part of a decentralized community health system.

    User question: {user_query}
    """

    #  Corrected: use "google_search" instead of deprecated "google_search_retrieval"
    data = {
        "contents": [
            {"role": "user", "parts": [{"text": prompt}]}
        ],
        "tools": [{"google_search": {}}],  # updated for new Gemini API
    }

    # Send request to Gemini API
    response = requests.post(url, headers=headers, params=params, json=data).json()

    #  Improved parsing for newer Gemini response format
    try:
        # Gemini may use "candidates" or "output" depending on endpoint version
        candidates = response.get("candidates", [])
        if not candidates:
            return f" No response candidates. Raw output: {response}"

        parts = candidates[0].get("content", {}).get("parts", [])
        if not parts:
            return f" No content parts found. Raw output: {response}"

        full_text = ""
        citations = []

        for part in parts:
            if "text" in part:
                full_text += part["text"] + "\n"
            elif "inline_data" in part:
                # Sometimes Gemini includes inline citations or structured data
                citations.append(str(part["inline_data"]))

        #  Extract any additional sources if available
        grounding = candidates[0].get("groundingMetadata", {})
        if "groundingChunks" in grounding:
            for chunk in grounding["groundingChunks"]:
                uri = chunk.get("web", {}).get("uri")
                if uri:
                    citations.append(uri)

        #  Combine clean response
        if citations:
            full_text += "\n🔗 Sources:\n" + "\n".join(citations)

        return full_text.strip() or "Sorry, I couldn't generate a response."
    except Exception as e:
        return f" Error parsing Gemini response: {e}\nRaw: {response}"

"""FASTAPI APP"""

app = FastAPI(title="Health AI Assistant (Gemini-2.5)", version="1.0")

@app.get("/")
def home():
    return {"message": " Health AI Assistant is running with Gemini-2.5 grounding."}

@app.get("/chat")
def chat(query: str = Query(..., description="User's health question")):
    result = get_gemini_response(query)
    return JSONResponse(content={
        "query": query,
        "response": result["response"],
        "citations": result["citations"]
    })

"""DEPLOY LOCALLY (FOR COLAB TESTING)"""

# ngrok.set_auth_token("YOUR_NGROK_AUTH_TOKEN")  # optional
# public_url = ngrok.connect(8000)
# print("Public URL:", public_url)
# nest_asyncio.apply()
# uvicorn.run(app, port=8000)

"""TEST THE CHATBOT LOCALLY"""

print(chatbot_response("What are the symptoms of malaria?"))
print(chatbot_response("How do I prevent cholera?"))

""" SAVE THE BOT AS app.py"""

chatbot_code = """{}""".format(open('/content/main.py', 'w').write(''))

# Create file with the full FastAPI code
app_code = '''
# === Health AI Assistant (Gemini 2.5) ===
import google.generativeai as genai
from fastapi import FastAPI, Query
from fastapi.responses import JSONResponse

genai.configure(api_key="YOUR_API_KEY_HERE")

model = genai.GenerativeModel(
    model_name="gemini-2.5-flash",
    tools=[{"google_search_retrieval": {}}]
)

SYSTEM_PROMPT = """You are a friendly, safe, non-diagnostic community health assistant."""
def build_prompt(user_query):
    return f"{SYSTEM_PROMPT}\\nUser: {user_query}"

def get_gemini_response(user_query):
    prompt = build_prompt(user_query)
    response = model.generate_content(prompt)
    return response.text.strip()

app = FastAPI(title="Health AI Assistant", version="1.0")

@app.get("/")
def home():
    return {"message": " Health AI Assistant running."}

@app.get("/chat")
def chat(query: str = Query(...)):
    reply = get_gemini_response(query)
    return JSONResponse(content={"query": query, "response": reply})
'''

with open("app.py", "w", encoding="utf-8") as f:
    f.write(app_code)

print(" app.py saved successfully! You can now share or deploy it.")