# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xfNBoADZ4UZg6Rg7Mcto3ik1uqbPriHq
"""

HEALTH_CHAIN_API_KEY="AIzaSyDMp1T7p16AAJqKcHLyN4uXoZsPrcvfgH4"

import os
from dotenv import load_dotenv

load_dotenv()

GEMINI_API_KEY = os.getenv("HEALTH_CHAIN_API_KEY")

# ==========================================
# Personalized Health Insights API (SECURE)
# ==========================================

from fastapi import FastAPI
from fastapi.responses import JSONResponse
from pydantic import BaseModel
import requests
import os
# from dotenv import load_dotenv # Removed as API key is directly available as a Python variable

#  Load environment variables
# load_dotenv() # Removed as API key is directly available as a Python variable

#  Get API key
GEMINI_API_KEY = HEALTH_CHAIN_API_KEY # Directly using the Python variable defined in the previous cell

#  Safety check
if not GEMINI_API_KEY:
    raise ValueError("API key not found. Please set HEALTH_CHAIN_API_KEY in .env file")

# Initialize FastAPI
app = FastAPI(title="Personalized Health Insights API")

# ============================
# Data Model
# ============================
class UserHealthData(BaseModel):
    age: int
    gender: str
    sleep_hours: float
    water_intake: str
    exercise_per_week: int
    symptoms: str = ""

# ============================
# AI Function
# ============================
def generate_insights(data: UserHealthData):

    prompt = f"""
    You are a friendly and safe health assistant.

    Provide personalized but NON-DIAGNOSTIC health insights.

    DO NOT diagnose diseases.

    User Data:
    - Age: {data.age}
    - Gender: {data.gender}
    - Sleep Hours: {data.sleep_hours}
    - Water Intake: {data.water_intake}
    - Exercise per week: {data.exercise_per_week}
    - Symptoms: {data.symptoms}

    Return:
    1. 3 short personalized insights
    2. 3 simple improvement tips
    """

    url = "https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent"

    headers = {
        "Content-Type": "application/json"
    }

    params = {
        "key": GEMINI_API_KEY
    }

    payload = {
        "contents": [
            {
                "role": "user",
                "parts": [{"text": prompt}]
            }
        ]
    }

    try:
        response = requests.post(url, headers=headers, params=params, json=payload)
        result = response.json()

        # Extract AI response
        text = result["candidates"][0]["content"]["parts"][0]["text"]
        return text

    except Exception as e:
        return f"Error: {response.text}"

# ============================
# API Endpoint
# ============================
@app.post("/insights")
def get_insights(user_data: UserHealthData):

    insights = generate_insights(user_data)

    return JSONResponse(content={
        "status": "success",
        "insights": insights
    })

# ============================
# Health Check Endpoint
# ============================
@app.get("/")
def root():
    return {"message": "Health Insights API is running "}

# Fake test object
class Dummy:
    age = 25
    gender = "male"
    sleep_hours = 4
    water_intake = "low"
    exercise_per_week = 0
    symptoms = "tired all the time"

print(generate_insights(Dummy))

app_code = """
# Paste your FULL personalized health insights code here
"""

with open("app.py", "w") as f:
    f.write(app_code)

print("✅ app.py saved successfully!")

from google.colab import files
files.download("app.py")